parameters:
  - name: 'ENV'
    displayName: 'Environment to deploy'
    type: string
    values:
      - dev
      - uat
      - prod
  - name: 'APP_NAME'
    displayName: 'Application to deploy'
    type: string
    values:
      - status

variables:
  ${{ if eq(parameters.ENV, 'uat') }}:
    kubernetesServiceConnection: '$(UAT_KUBERNETES_SERVICE_CONN)'
    selfHostedAgentPool: '$(UAT_AGENT_POOL)'

  ${{ if eq(parameters.ENV, 'prod') }}:
    kubernetesServiceConnection: '$(PROD_KUBERNETES_SERVICE_CONN)'
    selfHostedAgentPool: '$(PROD_AGENT_POOL)'

  ${{ if eq(parameters.ENV, 'dev') }}:
    kubernetesServiceConnection: '$(DEV_KUBERNETES_SERVICE_CONN)'
    selfHostedAgentPool: '$(DEV_AGENT_POOL)'

resources:
  repositories:
    - repository: templates
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v6.8.0
      endpoint: 'io-azure-devops-github-ro'

pool:
  name: $(selfHostedAgentPool)

name: "Deploy ${{ parameters.APP_NAME }} on ${{ parameters.ENV }} - $(Date:yyyyMMdd).$(Rev:r)"

stages:
  - template: templates/helm-microservice-chart-deploy-tree/template.yaml@templates
    parameters:
      ENV: ${{ parameters.ENV }}
      KUBERNETES_SERVICE_CONN: ${{ variables.kubernetesServiceConnection }}
      APP_NAME: ${{ parameters.APP_NAME }}
      CHART_PATH: "helm/${{parameters.ENV}}/${{parameters.APP_NAME}}"
      VALUE_FILE: "helm/${{parameters.ENV}}/${{parameters.APP_NAME}}/values.yaml"

  - stage: check_postman_test
    displayName: Check and run postman tests
    dependsOn: [helm_deploy]
    condition: succeeded()
    jobs:
      - job: get_postman_vars
        displayName: Get and Set Postman variables
        steps:
        - checkout: self
        - task: Bash@3
          displayName: 'Set variables'
          name: varsPostman
          inputs:
            targetType: 'inline'
            script: |
              echo "##vso[task.setvariable variable=nameRepo;isOutput=true]$(yq '.postman-test.nameRepo' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{parameters.APP_NAME}}/values.yaml )"
              echo "##vso[task.setvariable variable=dir;isOutput=true]$(yq '.postman-test.dir' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{parameters.APP_NAME}}/values.yaml )"
              echo "##vso[task.setvariable variable=collectionName;isOutput=true]$(yq '.postman-test.collectionName' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{parameters.APP_NAME}}/values.yaml )"
              echo "##vso[task.setvariable variable=envVariables;isOutput=true]$(yq '.postman-test.envVariables' $(Build.Repository.LocalPath)/helm/${{parameters.ENV}}/${{parameters.APP_NAME}}/values.yaml )"
        - task: Bash@3
          displayName: 'Print namespace variables'
          inputs:
            targetType: 'inline'
            script: |
              echo "nameRepo: $(varsPostman.nameRepo)"
              echo "dir: $(varsPostman.dir)"
              echo "collectionName: $(varsPostman.collectionName)"
              echo "envVariables: $(varsPostman.envVariables)"

      - job: postman_tests
        displayName: Postman Tests
        dependsOn: get_postman_vars
        variables:
          nameRepo: $[dependencies.get_postman_vars.outputs['varsPostman.nameRepo']]
          dir: $[dependencies.get_postman_vars.outputs['varsPostman.dir']]
          collectionName: $[dependencies.get_postman_vars.outputs['varsPostman.collectionName']]
          envVariable: $[dependencies.get_postman_vars.outputs['varsPostman.envVariables']]
        condition: and(succeeded(), ne(variables.nameRepo, 'null'),ne(variables.dir, 'null'),ne(variables.collectionName, 'null'),ne(variables.envVariable, 'null'))
        steps:
        - task: UseNode@1
          inputs:
            version: '20.x'
        - script: |
              git clone https://github.com/pagopa/$(nameRepo).git
              cd $(dir)
              npm install -g newman
              newman run $(collectionName) -e $(envVariable)
